name: Scout-actions
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: list files
        run: ls -la
      - name: do scout
        uses: coinfabrik/scout-actions@v2.2
        id: scout_test_id
        with:
          target: 'avoid-autokey-upgradable/avoid-autokey-upgradable-1/vulnerable-example/'
          scout_args: "--output-format md --output-path $GITHUB_OUTPUT"

      - name: Find comment
        id: find_comment
        uses: peter-evans/find-comment@v3
        with:
          token: ${{ secrets.CITOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "🎉 **Scout Report** 🎉"

      - name: Create or Update PR Comment
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          token: ${{ secrets.CITOKEN }}
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: replace
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🎉 **Scout Report** 🎉

            ${{join(steps.scout_test_id.outputs.*, '\n')}} 
            
            
            //needs.validate-detectors.outputs.status
            The workflow has completed. Great job! 🚀