name: Scout-actions
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: list files
        run: ls -la
      - name: do scout
        uses: coinfabrik/scout-actions@v2.1
        with:
          target: 'avoid-autokey-upgradable/avoid-autokey-upgradable-1/vulnerable-example/'